bind: 127.0.0.1:18080
backend: build/tests
gc:
  meta: 10s
  blob: 20s
caches:
  rocky:
    urls:
      - https://mirrors.ustc.edu.cn/rocky
      - https://mirror.sjtu.edu.cn/rocky
    rules:
      - regex: ".*.(db|xml|gz)"
        ttl: 30s
        refresh: 10s
      - regex: ".*.rpm"
        ttl: 1h
        refresh: 1m
