bind: 127.0.0.1:18080
backend: build/tests
gc:
  meta: 10s
  blob: 20s
caches:
  rocky:
    urls:
      - https://mirrors.ustc.edu.cn/rocky
      - https://mirror.sjtu.edu.cn/rocky
    rules:
      - regex: ".*.(db|xml|gz)"
        ttl: 1m
        refresh: 10s
      - regex: ".*.rpm"
        ttl: 1h
        refresh: 1m
  npm:
    urls:
      - https://registry.npmjs.org
    rules:
      - regex: ".*.tgz"
        ttl: "0s"
        refresh: "72h"
      - regex: ".*package\\.json"
        ttl: "0s"
        refresh: "12h"
      - regex: ".*\\.\\w"
        ttl: "120h"
        refresh: "10m"