bind: 127.0.0.1:18080
backend: build/tests
gc:
  meta: 10s
  blob: 20s
caches:
  rocky:
    urls:
      - https://mirrors.ustc.edu.cn/rocky
      - https://mirror.sjtu.edu.cn/rocky
    rules:
      - regex: ".*\\.(db|xml|gz|bz2)$"
        ttl: "20s"
        refresh: 10s
      - regex: ".*\\.(rpm|iso)$"
        ttl: "360h"
        refresh: 10s
  npm:
    transport:
      proxy: http://10.0.3.2:8889
    timeout: 1s
    urls:
      - https://registry.npmjs.org
    rules:
      - regex: ".*.tgz$"
        ttl: "1440h"
        refresh: "72h"
      - regex: ".*package\\.json$"
        ttl: "1440h"
        refresh: "12h"
    replaces:
      - regex: "^[A-Za-z0-9-_@]*(/[A-Za-z0-9-_@]*)*$"
        old: https://registry.npmjs.org
        new: https://mirrors.d7z.net/npm