package rpm

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"testing"

	"github.com/stretchr/testify/require"
)

// CC0 fixtures generated by zchunk 1.5.2 and published in the Kaitai Struct
// sample repository.
func TestDecompressZchunk(t *testing.T) {
	fixtures := []struct {
		encoded string
		plain   string
	}{
		{
			encoded: "AFpDSzGB7gXR0gqM0l51S3t8GbmV1sDvlsTK3Edp8Lr5NYJKynNAMBTTv4qeJ7Z591sq1y7Z1ZNJWL9PH16m6dKqUY6z4xOAgsqDhI0IJmcDf8gblAUukMx2PQm1rJEFWt2qPr+R2VBFYUW0GrWatWCOhxJgj2XcH2Utr9UhucOatfzpG87lY0zkyxcR9/kXfiKatYAotS/9ICxhAQB0aGUgcXVpY2sgYnJvd24gZm94IGp1bXBzIG92ZXIgdGhlIGxhenkgZG9nCii1L/0gNY0AAFBjaHVuayAxOiB0AQBgUyEBKLUv/SA1jQAAUGNodW5rIDI6IHQBAGBTIQEotS/9IDWNAABQY2h1bmsgMzogdAEAYFMhAQ==",
			plain:   "chunk 1: the quick brown fox jumps over the lazy dog\nchunk 2: the quick brown fox jumps over the lazy dog\nchunk 3: the quick brown fox jumps over the lazy dog\n",
		},
		{
			encoded: "AFpDSzGBbYGegrAzsrJnNKnYMNdbVk+Zma2q1S5ScaxprP9i5baI8wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAhIJIgYGDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICADvKVKz1625nGC9BPb8Vqn6J5LuOb14S7zyukjp2Gpl2COM7JLzJblNMwP4eZi4XBx8Pm1CFuXbem/7HjaoYrq5CH5Tk/VkIKmvNFd755IYm53yaQKnG7i0Z/MxOyTeS9AgDiWNJI/alMY3U2B/fESU7g/L6S8adr/ax5XJ2EEB6zF4+GgCi1L/0gBzkAAEhlbGxvLAootS/9IAYxAAB3b3JsZAo=",
			plain:   "Hello,\nworld\n",
		},
	}
	for _, fixture := range fixtures {
		wire, err := base64.StdEncoding.DecodeString(fixture.encoded)
		require.NoError(t, err)
		var output bytes.Buffer
		size, err := decompressZchunk(context.Background(), bytes.NewReader(wire), &output, 1<<20)
		require.NoError(t, err)
		require.Equal(t, int64(len(fixture.plain)), size)
		require.Equal(t, fixture.plain, output.String())
	}
}

func TestDecompressZchunkRejectsBoundsAndCancellation(t *testing.T) {
	wire, err := base64.StdEncoding.DecodeString("AFpDSzGB7gXR0gqM0l51S3t8GbmV1sDvlsTK3Edp8Lr5NYJKynNAMBTTv4qeJ7Z591sq1y7Z1ZNJWL9PH16m6dKqUY6z4xOAgsqDhI0IJmcDf8gblAUukMx2PQm1rJEFWt2qPr+R2VBFYUW0GrWatWCOhxJgj2XcH2Utr9UhucOatfzpG87lY0zkyxcR9/kXfiKatYAotS/9ICxhAQB0aGUgcXVpY2sgYnJvd24gZm94IGp1bXBzIG92ZXIgdGhlIGxhenkgZG9nCii1L/0gNY0AAFBjaHVuayAxOiB0AQBgUyEBKLUv/SA1jQAAUGNodW5rIDI6IHQBAGBTIQEotS/9IDWNAABQY2h1bmsgMzogdAEAYFMhAQ==")
	require.NoError(t, err)
	_, err = decompressZchunk(context.Background(), bytes.NewReader(wire), &bytes.Buffer{}, 1)
	require.ErrorContains(t, err, "output exceeds")
	_, err = decompressZchunk(context.Background(), bytes.NewReader(wire[:len(wire)-1]), &bytes.Buffer{}, 1<<20)
	require.Error(t, err)
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	_, err = decompressZchunk(ctx, bytes.NewReader(wire), &bytes.Buffer{}, 1<<20)
	require.ErrorIs(t, err, context.Canceled)
}

func TestInspectOpenMetadataValidatesZchunkOutput(t *testing.T) {
	wire, err := base64.StdEncoding.DecodeString("AFpDSzGBbYGegrAzsrJnNKnYMNdbVk+Zma2q1S5ScaxprP9i5baI8wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAhIJIgYGDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICADvKVKz1625nGC9BPb8Vqn6J5LuOb14S7zyukjp2Gpl2COM7JLzJblNMwP4eZi4XBx8Pm1CFuXbem/7HjaoYrq5CH5Tk/VkIKmvNFd755IYm53yaQKnG7i0Z/MxOyTeS9AgDiWNJI/alMY3U2B/fESU7g/L6S8adr/ax5XJ2EEB6zF4+GgCi1L/0gBzkAAEhlbGxvLAootS/9IAYxAAB3b3JsZAo=")
	require.NoError(t, err)
	plain := []byte("Hello,\nworld\n")
	digest := sha256.Sum256(plain)
	item := repomdItem{
		Location:     "repodata/primary.xml.zck",
		OpenSumType:  "sha256",
		OpenChecksum: hex.EncodeToString(digest[:]),
		OpenSize:     int64(len(plain)),
	}
	require.NoError(t, inspectOpenMetadataReader(context.Background(), bytes.NewReader(wire), int64(len(wire)), item))
	item.OpenSize++
	require.ErrorContains(t, inspectOpenMetadataReader(context.Background(), bytes.NewReader(wire), int64(len(wire)), item), "open-size mismatch")
}

func FuzzZchunk(f *testing.F) {
	f.Add([]byte("\x00ZCK1"))
	f.Add([]byte("not-zchunk"))
	f.Fuzz(func(t *testing.T, wire []byte) {
		if len(wire) > 1<<20 {
			t.Skip()
		}
		_, _ = decompressZchunk(context.Background(), bytes.NewReader(wire), &bytes.Buffer{}, 1<<20)
	})
}
