FROM docker.io/library/alpine:3.20 AS tools
RUN apk add --no-cache bash curl git

FROM docker.io/library/fedora:42 AS flatpak
RUN dnf install -y --setopt=install_weak_deps=False flatpak && dnf clean all

FROM docker.io/library/maven:3.9-eclipse-temurin-21-alpine AS maven
RUN mvn -B -ntp org.apache.maven.plugins:maven-dependency-plugin:3.8.1:help >/dev/null
